session_name: lestnicyrf
windows:
  - window_name: console
    panes:
      -
  - window_name: editor
    panes:
      - vim
  - window_name: server
    panes:
      - jekyll serve
      - gulp watch

