# General
session_name: lestnicyrf

# Windows
windows:
  - window_name: bash
    panes:
      - shell_command:
        - nvm use 0
  - window_name: vim
    panes:
      - shell_command:
        - nvm use 0
        - vim
  - window_name: misc
    panes:
      - shell_command:
        - nvm use 0
        - gulp
