# General
session_name: lestnicy+rf

# Windows
windows:
  - window_name: bash
    panes:
      - shell_command:
        -
  - window_name: vim
    panes:
      - shell_command:
        - vim
  - window_name: proc
    panes:
      - shell_command:
        -
