# Jekyll configuration
---

# Base
title: Лестницы.рф
description: "Готовые деревянные лестницы"
github: lestnicatmpru
url: "http://лестницы.рф"
permalink: /blog/:title/:year-:month-:day/
data_source: ./_database
sass: {sass_dir: styles/_sass}
exclude: [CNAME, README.md]
 
# Collections
collections:
  articles:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page
  
# Translators
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    