# Base
url: "http://лестницы.рф"
title: Лестницы.рф
description: "Готовые деревянные лестницы"
keywords: деревянные лестницы
permalink: /блог/:title/:year-:month-:day/
data_source: ./_database
sass: {sass_dir: styles/_sass}
exclude: [CNAME, README.md]

# Collections
collections:
  contents:
    output: true
    permalink: /:path/
  test:
    output: true
    permalink: /:path/
 
# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: home
  
# Translators
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    